# Generated by Django 5.1.7 on 2025-06-26 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_petdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petdata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
